# Generated by Django 6.0.5 on 2026-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
