# Generated by Django 6.0.5 on 2026-05-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_source_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='company',
        ),
        migrations.RemoveField(
            model_name='source',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='source',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], default='India', max_length=100),
            preserve_default=False,
        ),
    ]
