# Generated by Django 6.0.5 on 2026-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='total_emissions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='scope',
            field=models.CharField(choices=[('Scope 1', 'Scope 1'), ('Scope 2', 'Scope 2'), ('Scope 3', 'Scope 3')], max_length=50),
        ),
    ]
