# Generated by Django 6.0.5 on 2026-05-25 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='emission_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissionrecord'),
        ),
    ]
